alias lg='lazygit'
alias j='nvim'
alias t='tmux'
alias tk='tmux kill-server'

export PATH="$HOME/.local/bin:$PATH"  # pipx でインストールしたコマンド用
export PATH="$HOME/.local/scripts:$PATH"
export PATH="$HOME/.config/tmux-sessionizer:$PATH"

bindkey -s ^f "tmux-sessionizer\n"
bindkey -s ^s "source ~/.zshrc\n"

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

