#!/bin/bash

# =========================================================================

# PATH 環境変数の設定

# -------------------------------------------------------------------------

# 各種コマンドの検索パスを管理します。

# ユーザー固有のパスがシステムのパスより優先されるように、先頭に追加します。

# =========================================================================

export PATH="$HOME/.local/bin:$PATH"  # pipx でインストールしたコマンド用

export PATH="$(go env GOPATH)/bin:$PATH" # Go言語のバイナリパス

export PATH="$PATH:/Applications/WezTerm.app/Contents/MacOS" # WezTerm



# =========================================================================

# エイリアス (alias) の設定

# -------------------------------------------------------------------------

# よく使うコマンドを短い名前で実行できるようにします。

# =========================================================================

alias s1='ssh s1'

alias s2='ssh s2'

alias s3='ssh s3'

alias s4='ssh s4'

alias s5='ssh s5'

alias lg='lazygit'

alias typ='typst compile --root /'

alias j='nvim'

alias ta='tmux a'

alias tk='tmux kill-server'

alias tx='tmux'

export PATH="$HOME/.local/scripts:$PATH"
# /Users/fukushimahideto/dotfiles/tmux-sessionizer/tmux-sessionizer
export PATH="$HOME/dotfiles/tmux-sessionizer:$PATH"

bindkey -s ^f "tmux-sessionizer\n"
bindkey -s ^k "nvim\n"
bindkey -s '\eh' "tmux-sessionizer -s 0\n"
bindkey -s '\et' "tmux-sessionizer -s 1\n"
bindkey -s '\en' "tmux-sessionizer -s 2\n"
bindkey -s '\es' "tmux-sessionizer -s 3\n"

