
# set-option -a terminal-features 'xterm-256color:RGB'
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=blue bold"
set -g status-right ""
set -g status-left "#S"

bind r source-file "/Users/fukushimahideto/.config/tmux/tmux.conf"
bind b set -g status
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi V send-keys -X select-line

# Ctrl-space + h で水平にペインを分割
bind p split-window -hl 60
# ウィンドウの移動
bind h previous-window
bind l next-window

# kill pane without confirmation
bind w kill-pane

# tmux resurrect
run-shell ~/tmux-resurrect/resurrect.tmux
# prefix + Ctrl-s - save
# prefix + Ctrl-r - restore
# ~/.config/tmux/tmux.conf にsymlink をはること
# ln -s ~/dotfiles/.tmux.conf ~/.config/tmux/tmux.conf
