" =============================================================================
" ~/.vimrc
" Neovim init.lua からの移植版
" プラグイン / LSP / 補完 / Treesitter / diagnostics なし
" =============================================================================

set nocompatible
set encoding=utf-8
scriptencoding utf-8

" -----------------------------------------------------------------------------
" leader
" -----------------------------------------------------------------------------
let mapleader = ";"
let maplocalleader = ";"

" -----------------------------------------------------------------------------
" vim-plug
" -----------------------------------------------------------------------------
call plug#begin()
Plug 'lambdalisue/vim-fern'
Plug 'tpope/vim-sensible'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-commentary'
Plug 'easymotion/vim-easymotion'
Plug 'ojroques/vim-oscyank', {'branch': 'main'}
call plug#end()

" -----------------------------------------------------------------------------
" 基本
" -----------------------------------------------------------------------------
filetype plugin indent on
syntax enable

set mouse=
set noswapfile
set number
set nocursorcolumn
set smartindent

set tabstop=2
set shiftwidth=2

" 元の init.lua には expandtab は無かったので、いったん無効のまま。
" Python/Rを書くなら filetype 別設定で有効化する。
" set expandtab

set ignorecase
set smartcase
set incsearch
set hlsearch

set backspace=indent,eol,start
set scrolloff=5
set sidescrolloff=5
set splitbelow
set splitright
set autoread
set confirm
set history=10000

" Ctrl-a / Ctrl-x で 08 などを8進数扱いしない
set nrformats-=octal

" Vim ではバッファ移動時に未保存バッファを隠せるようにしておく
set hidden

" Neovim diagnostics 用だったが、Vimでも軽いので残す
set updatetime=200

" Vimのバージョン差で壊れないように条件付き
if exists('&signcolumn')
	set signcolumn=yes
endif

if exists('&wildignorecase')
	set wildignorecase
endif

" -----------------------------------------------------------------------------
" 行折り返し設定
" wrap=true を維持
" -----------------------------------------------------------------------------
set wrap
set linebreak

if exists('&breakindent')
	set breakindent
endif

let &showbreak = repeat(' ', 3)

" wrap時は表示行単位で上下移動
nnoremap <expr> j v:count == 0 ? 'gj' : 'j'
nnoremap <expr> k v:count == 0 ? 'gk' : 'k'

" -----------------------------------------------------------------------------
" クリップボード
" -----------------------------------------------------------------------------
" ローカルMacのVimなど、+clipboard がある環境では system clipboard を使う。
" SSH先のVimでは +clipboard が無いことも多いので、条件分岐にする。
if has('clipboard')
	if has('unnamedplus')
		set clipboard=unnamedplus
	else
		set clipboard=unnamed
	endif
endif

" -----------------------------------------------------------------------------
" 補完・検索・コマンドライン補助
" -----------------------------------------------------------------------------
set completeopt=menu,menuone,noselect

set wildmenu
set wildmode=longest:full,full

" :find で再帰的にファイル検索できるようにする
set path+=**

set wildignore+=*/.git/*
set wildignore+=*/node_modules/*
set wildignore+=*/__pycache__/*
set wildignore+=*.pyc

" ripgrep があれば :grep に使う
if executable('rg')
	set grepprg=rg\ --vimgrep\ --smart-case
	set grepformat=%f:%l:%c:%m
endif

" -----------------------------------------------------------------------------
" persistent undo
" Vimを閉じた後でもundo履歴を残す
" -----------------------------------------------------------------------------
if has('persistent_undo')
	set undofile

	let s:undo_dir = expand('~/.vim/undo')

	if !isdirectory(s:undo_dir)
		call mkdir(s:undo_dir, 'p')
	endif

	let &undodir = s:undo_dir . '//'
endif

" -----------------------------------------------------------------------------
" formatoptions
" コメント行で Enter / o / O したとき、勝手にコメントを継続しない
" -----------------------------------------------------------------------------
augroup my_formatoptions
	autocmd!
	autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
augroup END

" -----------------------------------------------------------------------------
" filetype別インデント
" -----------------------------------------------------------------------------
augroup my_filetype_indent
	autocmd!

	" Pythonは基本4スペース
	autocmd FileType python setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

	" R / Rmd は2スペース
	autocmd FileType r,rmd,rmarkdown setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2

	" shell系も2スペース
	autocmd FileType sh,zsh,bash setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2

	" Makefileはタブが意味を持つのでスペース化しない
	autocmd FileType make setlocal noexpandtab
augroup END

" -----------------------------------------------------------------------------
" netrw
" Oil の代替。
" <leader>e で常にカレントディレクトリを開く。
" -----------------------------------------------------------------------------
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 0
let g:netrw_winsize = 25

nnoremap <leader>e :Explore .<CR>

" -----------------------------------------------------------------------------
" fzf
" 元の <leader>ff :FZF は残す。
" 追加で fzf.vim の便利コマンドを割り当てる。
" -----------------------------------------------------------------------------
let g:fzf_layout = { 'down': '40%' }

let g:fzf_vim = {}
let g:fzf_vim.preview_window = ['right,50%,<70(up,40%)', 'ctrl-/']

" 元からあるFZF起動
nnoremap <leader>ff :FZF<CR>

" fzf.vimの追加コマンド
nnoremap <leader>fF :Files<CR>
nnoremap <leader>fg :GFiles<CR>
nnoremap <leader>fb :Buffers<CR>
nnoremap <leader>fh :History<CR>
nnoremap <leader>fl :Lines<CR>
nnoremap <leader>fL :BLines<CR>
nnoremap <leader>fc :Commands<CR>
nnoremap <leader>fm :Marks<CR>

" 元からあるRg起動
nnoremap <leader>fr :Rg<CR>

" カーソル下の単語でripgrep
if executable('rg')
	nnoremap <leader>fw :Rg <C-r><C-w><CR>
endif

" -----------------------------------------------------------------------------
" コアキーマップ
" -----------------------------------------------------------------------------

" insert mode escape
inoremap jk <Esc>

" スクロール後にカーソルを中央へ
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz

" 検索ハイライトを消す
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>

" visual indent 後に選択を維持
xnoremap < <gv
xnoremap > >gv

" 保存・終了
nnoremap <leader>w :write<CR>
nnoremap <leader>q :quit<CR>
nnoremap <leader>Q :wqa<CR>

" バッファ操作
nnoremap <leader>a :edit #<CR>

nnoremap <leader>da :%bdelete!<CR>
nnoremap <leader>dd :%bdelete<CR>

" 無名レジスタの内容を shell command として実行
" Neovim側の <leader>xx 相当
nnoremap <leader>xx :execute '!' . getreg('"')<CR>

" tmux-sessionizer
if executable('tmux')
	nnoremap <C-g> :silent !tmux neww tmux-sessionizer<CR>:redraw!<CR>
endif

" sn でスニペットを挿入
command! Snippet read !sn
nnoremap <silent> <leader>s :Snippet<CR>A<Esc>


" vimrc再読み込み
nnoremap <leader>vs :source $MYVIMRC<CR>

" 整形・選択
nnoremap <leader>gg gg=G
nnoremap <leader>gd ggVG

" -----------------------------------------------------------------------------
" whitespace
" -----------------------------------------------------------------------------
set listchars=tab:>-,trail:·,extends:>,precedes:<,nbsp:+

" 不可視文字表示トグル
nnoremap <leader>l :set list!<CR>

" 末尾空白削除
command! Trim keeppatterns %s/\s\+$//e
nnoremap <leader>tw :Trim<CR>

" -----------------------------------------------------------------------------
" ローマ字文を日本語文に変換する
" -----------------------------------------------------------------------------
command! -range R2J <line1>,<line2>!r2j

" normal mode: 現在の段落を日本語化
nnoremap <silent> <leader>z vip:R2J<CR>

" visual mode: 選択範囲を日本語化
xnoremap <silent> <leader>z :R2J<CR>




" =============================================================================
" OSC52 clipboard yank
" =============================================================================

let g:oscyank_silent = 1
let g:oscyank_max_length = 0

augroup VimOSCYankPost
	autocmd!
	autocmd TextYankPost * if v:event.operator ==# 'y' | call OSCYankRegister(v:event.regname) | endif
augroup END
