" =============================================================================
" ~/.vimrc
" Neovim init.lua からの移植版
" プラグイン / LSP / 補完 / Treesitter / diagnostics なし
" =============================================================================

set nocompatible
set encoding=utf-8
scriptencoding utf-8


" -----------------------------------------------------------------------------
" leader
" -----------------------------------------------------------------------------
let mapleader = " "
let maplocalleader = ";"

" -----------------------------------------------------------------------------
" vim-plug
" -----------------------------------------------------------------------------
call plug#begin()
Plug 'lambdalisue/vim-fern'
Plug 'terryma/vim-expand-region'
Plug 'yuki-yano/fern-preview.vim'
Plug 'tpope/vim-sensible'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-commentary'
Plug 'easymotion/vim-easymotion'
Plug 'ojroques/vim-oscyank', {'branch': 'main'}
call plug#end()

" -----------------------------------------------------------------------------
" 基本
" -----------------------------------------------------------------------------
filetype plugin indent on
syntax enable

set mouse=
set noswapfile
set number
set nocursorcolumn
set smartindent

set tabstop=2
set shiftwidth=2

" 元の init.lua には expandtab は無かったので、いったん無効のまま。
" Python/Rを書くなら filetype 別設定で有効化する。
" set expandtab

set ignorecase
set smartcase
set incsearch
set hlsearch

set backspace=indent,eol,start
set scrolloff=5
set sidescrolloff=5
set splitbelow
set splitright
set autoread
set confirm
set history=10000

" Ctrl-a / Ctrl-x で 08 などを8進数扱いしない
set nrformats-=octal

" Vim ではバッファ移動時に未保存バッファを隠せるようにしておく
set hidden

" Neovim diagnostics 用だったが、Vimでも軽いので残す
set updatetime=200

" Vimのバージョン差で壊れないように条件付き
if exists('&signcolumn')
	set signcolumn=yes
endif

if exists('&wildignorecase')
	set wildignorecase
endif

" -----------------------------------------------------------------------------
" 行折り返し設定
" wrap=true を維持
" -----------------------------------------------------------------------------
set wrap
set linebreak

if exists('&breakindent')
	set breakindent
endif

let &showbreak = repeat(' ', 3)

" wrap時は表示行単位で上下移動
nnoremap <expr> j v:count == 0 ? 'gj' : 'j'
nnoremap <expr> k v:count == 0 ? 'gk' : 'k'

" -----------------------------------------------------------------------------
" クリップボード
" -----------------------------------------------------------------------------
" ローカルMacのVimなど、+clipboard がある環境では system clipboard を使う。
" SSH先のVimでは +clipboard が無いことも多いので、条件分岐にする。
if has('clipboard')
	if has('unnamedplus')
		set clipboard=unnamedplus
	else
		set clipboard=unnamed
	endif
endif

" -----------------------------------------------------------------------------
" Vim標準 autocomplete / fuzzy completion
" -----------------------------------------------------------------------------

if exists('+autocomplete')
	set autocomplete
endif

if exists('+autocompletedelay')
	set autocompletedelay=120
endif

set completeopt=menu,menuone,noselect,fuzzy

" Vim 9.1.1178〜9.1.1929では、
" completeopt=fuzzyとは別にfuzzy候補収集の指定が必要
"
" Vim 9.1.1930以降ではdeprecatedで効果はないが、
" 設定してもエラーにならないため互換性目的で残す
if exists('+completefuzzycollect')
	set completefuzzycollect=keyword,files,whole_line
endif
set wildmenu
set wildmode=longest:full,full

" :find で再帰的にファイル検索できるようにする
set path+=**

set wildignore+=*/.git/*
set wildignore+=*/node_modules/*
set wildignore+=*/__pycache__/*
set wildignore+=*.pyc

" ripgrep があれば :grep に使う
if executable('rg')
	set grepprg=rg\ --vimgrep\ --smart-case
	set grepformat=%f:%l:%c:%m
endif

" -----------------------------------------------------------------------------
" formatoptions
" コメント行で Enter / o / O したとき、勝手にコメントを継続しない
" -----------------------------------------------------------------------------
augroup my_formatoptions
	autocmd!
	autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
augroup END

" -----------------------------------------------------------------------------
" filetype別インデント
" -----------------------------------------------------------------------------
augroup my_filetype_indent
	autocmd!

	" Pythonは基本4スペース
	autocmd FileType python setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

	" R / Rmd は2スペース
	autocmd FileType r,rmd,rmarkdown setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2

	" shell系も2スペース
	autocmd FileType sh,zsh,bash setlocal expandtab tabstop=2 shiftwidth=2 softtabstop=2

	" Makefileはタブが意味を持つのでスペース化しない
	autocmd FileType make setlocal noexpandtab
augroup END

" -----------------------------------------------------------------------------
" fern
" Oil の代替。
" <leader>e で常にカレントディレクトリを開く。
" -----------------------------------------------------------------------------
nnoremap <leader>e :Fern .<CR>

" -----------------------------------------------------------------------------
" fzf
" 元の <leader>ff :FZF は残す。
" 追加で fzf.vim の便利コマンドを割り当てる。
" -----------------------------------------------------------------------------
let g:fzf_layout = { 'down': '40%' }

let g:fzf_vim = {}
let g:fzf_vim.preview_window = ['right,50%,<70(up,40%)', 'ctrl-/']

" 元からあるFZF起動
nnoremap <leader>ff :FZF<CR>

" fzf.vimの追加コマンド
nnoremap <leader>fF :Files<CR>
nnoremap <leader>fg :GFiles<CR>
nnoremap <leader>fb :Buffers<CR>
nnoremap <leader>fh :History<CR>
nnoremap <leader>fl :Lines<CR>
nnoremap <leader>fL :BLines<CR>
nnoremap <leader>fc :Commands<CR>
nnoremap <leader>fm :Marks<CR>

" 元からあるRg起動
nnoremap <leader>fr :Rg<CR>

" カーソル下の単語でripgrep
if executable('rg')
	nnoremap <leader>fw :Rg <C-r><C-w><CR>
endif

" -----------------------------------------------------------------------------
" コアキーマップ
" -----------------------------------------------------------------------------

" insert mode escape
inoremap jk <Esc>

" スクロール後にカーソルを中央へ
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz

" 検索ハイライトを消す
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>

" visual indent 後に選択を維持
xnoremap < <gv
xnoremap > >gv

" 保存・終了
nnoremap <leader>w :write<CR>
nnoremap <leader>q :quit<CR>
nnoremap <leader>Q :wqa<CR>

" バッファ操作
nnoremap <leader>a :edit #<CR>

nnoremap <leader>da :%bdelete!<CR>
nnoremap <leader>dd :%bdelete<CR>

" 無名レジスタの内容を shell command として実行
" Neovim側の <leader>xx 相当
nnoremap <leader>xx :execute '!' . getreg('"')<CR>

" tmux-sessionizer
if executable('tmux')
	nnoremap <C-g> :silent !tmux neww tmux-sessionizer<CR>:redraw!<CR>
endif

" sn でスニペットを挿入
command! Snippet read !sn
nnoremap <silent> <C-n>sn :Snippet<CR>A<Esc>


" vimrc再読み込み
nnoremap <leader>vs :source $MYVIMRC<CR>

" 整形・選択
nnoremap <leader>gg gg=G
nnoremap <leader>gd ggVG

" -----------------------------------------------------------------------------
" whitespace
" -----------------------------------------------------------------------------
set listchars=tab:>-,trail:·,extends:>,precedes:<,nbsp:+

" 不可視文字表示トグル
nnoremap <leader>l :set list!<CR>

" 末尾空白削除
command! Trim keeppatterns %s/\s\+$//e
nnoremap <leader>tw :Trim<CR>

" -----------------------------------------------------------------------------
" ローマ字文を日本語文に変換する
" -----------------------------------------------------------------------------
command! -range R2J <line1>,<line2>!r2j

" normal mode: 現在の段落を日本語化
nnoremap <silent> <leader>z vip:R2J<CR>

" visual mode: 選択範囲を日本語化
xnoremap <silent> <leader>z :R2J<CR>

" =============================================================================
" Smart clipboard yank debug version
" =============================================================================

let g:oscyank_silent = 1
let g:oscyank_max_length = 0
let g:smart_clip_debug = 0

function! SmartClipboardDebug(msg) abort
	if get(g:, 'smart_clip_debug', 0)
		echom '[smart-clip] ' . a:msg
	endif
endfunction

function! IsRemoteSession() abort
	return exists('$SSH_CONNECTION') || exists('$SSH_TTY')
endfunction

function! CopyRegisterToSystemClipboard(reg) abort
	let l:reg = empty(a:reg) ? '"' : a:reg
	let l:text = getreg(l:reg)
	let l:type = getregtype(l:reg)

	call SmartClipboardDebug('reg=' . string(l:reg))
	call SmartClipboardDebug('len=' . strlen(l:text))
	call SmartClipboardDebug('type=' . string(l:type))
	call SmartClipboardDebug('has_clipboard=' . has('clipboard'))
	call SmartClipboardDebug('has_macunix=' . has('macunix'))
	call SmartClipboardDebug('pbcopy=' . executable('pbcopy'))
	call SmartClipboardDebug('remote=' . IsRemoteSession())
	call SmartClipboardDebug('OSCYankRegister=' . exists('*OSCYankRegister'))

	if empty(l:text)
		call SmartClipboardDebug('ERROR: register is empty')
		return
	endif

	" Remote SSH: OSC52
	if IsRemoteSession()
		call SmartClipboardDebug('branch=remote/oscyank')
		if exists('*OSCYankRegister')
			call OSCYankRegister(l:reg)
			call SmartClipboardDebug('done=OSCYankRegister')
			return
		endif
		call SmartClipboardDebug('ERROR: OSCYankRegister does not exist')
		return
	endif

	" Local macOS: prefer pbcopy
	if has('macunix') && executable('pbcopy')
		call SmartClipboardDebug('branch=local/pbcopy')
		call system('pbcopy', l:text)
		call SmartClipboardDebug('pbcopy_shell_error=' . v:shell_error)
		return
	endif

	" Local Vim with clipboard support
	if has('clipboard')
		call SmartClipboardDebug('branch=local/+register')
		call setreg('+', l:text, l:type)
		call setreg('*', l:text, l:type)
		call SmartClipboardDebug('done=setreg +/*')
		return
	endif

	" Last fallback: OSC52
	if exists('*OSCYankRegister')
		call SmartClipboardDebug('branch=fallback/oscyank')
		call OSCYankRegister(l:reg)
		call SmartClipboardDebug('done=OSCYankRegister fallback')
		return
	endif

	call SmartClipboardDebug('ERROR: no clipboard method available')
endfunction

augroup VimSmartYankPost
	autocmd!
	autocmd TextYankPost * if v:event.operator ==# 'y' | call CopyRegisterToSystemClipboard(v:event.regname) | endif
augroup END


" =============================================================================
" fern path yank -> smart clipboard
" =============================================================================

function! FernPathYankAndCopy() abort
	let l:helper = fern#helper#new()
	let l:nodes = l:helper.sync.get_selected_nodes()

	if empty(l:nodes)
		let l:nodes = [l:helper.sync.get_cursor_node()]
	endif

	let l:paths = []

	for l:node in l:nodes
		if has_key(l:node, '_path')
			call add(l:paths, l:node._path)
		elseif has_key(l:node, 'path')
			call add(l:paths, l:node.path)
		elseif has_key(l:node, 'bufname') && type(l:node.bufname) == type('')
			call add(l:paths, l:node.bufname)
		endif
	endfor

	if empty(l:paths)
		echohl ErrorMsg
		echom '[smart-clip] ERROR: fern path not found'
		echom '[smart-clip] node=' . string(l:nodes)
		echohl None
		return
	endif

	let l:text = join(l:paths, "\n")

	call setreg('"', l:text, len(l:paths) > 1 ? 'V' : 'v')
	call CopyRegisterToSystemClipboard('"')

	echom '[smart-clip] copied fern path: ' . l:text
endfunction

function! FernSmartYankInit() abort
	nnoremap <buffer><silent> y :<C-u>call FernPathYankAndCopy()<CR>
endfunction

augroup FernSmartYank
	autocmd!
	autocmd FileType fern call FernSmartYankInit()
augroup END

" =============================================================================
" fern-preview settings
" 自動preview ON。ただし巨大ファイル・バイナリ・圧縮ファイルは避ける
" =============================================================================

let g:fern_auto_preview = v:true

" 300 KB以上はpreviewしない
" 重ければ 100 * 1000、ゆるくするなら 1000 * 1000 くらい
let g:fern_preview_max_filesize = 300 * 1000

" previewしない拡張子
let g:fern_preview_ignore_extensions = [
			\ 'gif', 'jpeg', 'jpg', 'png', 'tif', 'tiff', 'wbmp', 'ico',
			\ 'pdf', 'ps', 'ai', 'rtf',
			\ 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx',
			\ 'bam', 'bai', 'cram', 'crai',
			\ 'fastq', 'fastq.gz', 'fq', 'fq.gz',
			\ 'sam',
			\ 'rds', 'RData',
			\ 'jar', 'war', 'ear',
			\ 'so', 'a', 'lib', 'dll', 'exe', 'bin',
			\ 'dmg', 'iso', 'msi', 'deb', 'rpm',
			\ 'mp3', 'ogg', 'mp4', 'mpeg', 'mpg', 'mov', 'webm', 'flv', 'wmv', 'avi',
			\ 'wasm', 'min.js', 'js.map'
			\ ]

function! s:fern_settings() abort
	" previewを手動で開閉
	nmap <silent> <buffer> p <Plug>(fern-action-preview:toggle)

	" auto preview ON/OFF
	nmap <silent> <buffer> P <Plug>(fern-action-preview:auto:toggle)

	" preview windowをスクロール
	nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
	nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)

	" q: previewが開いていればpreviewを閉じる。開いていなければfernを閉じる。
	nmap <silent> <buffer> <expr> <Plug>(fern-quit-or-close-preview) fern_preview#smart_preview("\<Plug>(fern-action-preview:close)", ":q\<CR>")
	nmap <silent> <buffer> q <Plug>(fern-quit-or-close-preview)
endfunction

augroup fern-settings
	autocmd!
	autocmd FileType fern call s:fern_settings()
augroup END

" fernを開く
nnoremap <silent> <leader>e :Fern . -reveal=%<CR>





" ============================================================
" terryna
" ============================================================
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

" ============================================================
" R関連
" ============================================================
inoremap <silent> <localleader>l <- 
inoremap <silent> <localleader>p %>% 
