
# set -gq allow-passthrough on
set -s set-clipboard on

# --- Leader key ---
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# --- Window / Pane 操作 ---
bind h previous-window
bind l next-window
bind k kill-pane
bind n new-window

# --- カスタム起動 ---
bind-key -r g run-shell "tmux neww ~/dotfiles/tmux-sessionizer/tmux-sessionizer"

