set -g renumber-windows on
set -gq allow-passthrough on
bind s split-window -v
bind h previous-window
bind l next-window
bind k kill-pane
bind n new-window


bind-key -n M-Left resize-pane -L 1
bind-key -n M-Right resize-pane -R 1
bind-key -n M-Up resize-pane -U 1
bind-key -n M-Down resize-pane -D 1
bind-key -r f run-shell "tmux neww ~/dotfiles/tmux-sessionizer/tmux-sessionizer"

