
# set -gq allow-passthrough on
set -s set-clipboard on

# --- Leader key ---
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# --- Window / Pane 操作 ---
bind v split-window -v
bind h previous-window
bind l next-window
bind k kill-pane
bind n new-window
bind g run "~/dotfiles/tmux/open-github.sh"

# --- Pane resize (Alt + Arrow) ---
bind-key -n M-Left  resize-pane -L 1
bind-key -n M-Right resize-pane -R 1
bind-key -n M-Up    resize-pane -U 1
bind-key -n M-Down  resize-pane -D 1

# --- カスタム起動 ---
bind-key -r g run-shell "tmux neww ~/dotfiles/tmux-sessionizer/tmux-sessionizer"

