# Ghostty shell integration for Bash. This should be at the top of your bashrc!
if [ -n "${GHOSTTY_RESOURCES_DIR}" ]; then
    builtin source "${GHOSTTY_RESOURCES_DIR}/shell-integration/zsh/ghostty-integration"
fi


alias tk='tmux kill-server'
alias v='vim'
alias r='Rscript'
alias p='python3'

export PATH="$HOME/.local/scripts:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.config/tmux-sessionizer:$PATH"
export PATH="$HOME/.fzf/bin:$PATH"

bindkey -s ^g "tmux-sessionizer\n"
bindkey -s ^t "~/dotfiles/newproj\n"
bindkey -s ^v "vim\n"
bindkey -s ^n "nvim\n"





[ -f "/Users/fukushimahideto/.ghcup/env" ] && . "/Users/fukushimahideto/.ghcup/env" # ghcup-env
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'
export FZF_DEFAULT_OPTS='--layout=reverse --height=40% --border'
export FZF_CTRL_T_COMMAND='fd --type f --hidden --exclude .git --exclude node_modules --exclude Library'
export FZF_CTRL_T_OPTS="
  --preview 'bat --style=numbers --color=always --line-range=:200 {}'
  "

export PATH="/opt/homebrew/bin:$PATH"
